#!/bin/bash

# This script moves all the images into a folder called "images" until you stop it

while true; do
	
	echo "Image sorter is on!"
	echo "If you want to stop press CTRL + C !"
	mv *.png images
	mv *.jpg images
	mv *.jpeg images
	mv *.webp images
	sleep 1


done
